- name: Validando Hosts
  hosts: all
  gather_facts: yes

  vars:
    installer: 'C:\Temp\apache-tomcat-11.0.22.exe'
    installer1: 'C:\Temp\jre-8u491-windows-x64.exe'
    install_args: '/S /C=C:\Temp\configs_tomcat.txt'
    install_args1: '/s'
    
  tasks:
   - name: Copiar arquivos da nova versão
     ansible.windows.win_shell: |
       net use \\fileserver.scl.corp\dsl /user:SCL\n1-np-dtc-jeac2 Entrar@2576
       copy "\\fileserver.scl.corp\dsl\02_APLICATIVOS\Apache Tomcat\apache-tomcat-11.0.22.exe" "C:\temp\"
       copy "\\fileserver.scl.corp\dsl\02_APLICATIVOS\Apache Tomcat\jre-8u491-windows-x64.exe" "C:\temp\jre-8u491-windows-x64.exe"
       copy "\\fileserver.scl.corp\dsl\02_APLICATIVOS\Apache Tomcat\configs_tomcat.txt" "C:\temp\"
       net use \\fileserver.scl.corp\dsl /delete

   - name: Parando service
     win_service:
       name: Tomcat10
       state: stopped
     ignore_errors: yes

   - name: removendo service residual
     win_command: sc delete Tomcat10
     ignore_errors: yes
   
   - name: Desinstalar Tomcat10 via uninstaller
     win_command: >
       "C:\Program Files\Apache Software Foundation\Tomcat 10.0\uninstall.exe" /S

   - name: Instalar JRE nova versao
     win_package: 
       path: "{{ installer1 }}"
       arguments: "{{ install_args1 }}"
       state: present
       expected_return_code: [0, 3010]

   - name: Instalar nova versao
     win_package: 
       path: "{{ installer }}"
       arguments: "{{ install_args }}"
       state: present
       expected_return_code: [0, 3010]

   - name: Deletando installer
     ansible.windows.win_file:
      path: "{{ installer }}"
      state: absent
